name: CCViM
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.9
- torchvision==0.14.0
- torchaudio==0.13.0
- timm==0.4.12
- triton==2.0.0
- packaging
- pytest
- chardet
- yacs
- termcolor
- submitit
- tensorboardX
- scikit-learn
- matplotlib
- h5py
- SimpleITK
- scikit-image
- medpy
- pip:
    - mamba_ssm==1.0.1
    - causal_conv1d==1.0.0
    - opencv-python==4.9.0.80
    - thop
    - docopt
    - imgaug
    - psutil
    - pandas